// <auto-generated />
using System;
using KSS.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180918205602_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KSS.Areas.Admin.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new { CategoryId = 1, Name = "CPR" },
                        new { CategoryId = 2, Name = "BLS" },
                        new { CategoryId = 3, Name = "AED" },
                        new { CategoryId = 4, Name = "EMT" }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookAvailable");

                    b.Property<decimal>("BookPrice");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("PrereqId");

                    b.Property<int>("TypicalPrice");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrereqId");

                    b.ToTable("Course");

                    b.HasData(
                        new { CourseId = 1, BookAvailable = true, BookPrice = 25m, CategoryId = 1, Description = "A 4 ½ hour initial course designed for Healthcare Professionals.  The course covers Adult, Child, and Infant one-rescuer CPR AED, as well as a new focused emphasis on teamwork with the adult, child, and infant two-person rescue.  Topics also include Rescue Breathing and Foreign Body Airway Obstruction. Cost includes the use of a textbook, written and practical exams, and a course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Basic Life Support (BLS) for Healthcare Professionals", TypicalPrice = 50 },
                        new { CourseId = 2, BookAvailable = false, BookPrice = 0m, CategoryId = 2, Description = "A 4 hour refresher course for the Healthcare Professional; this course offers guidelines in one and two-rescuer adult, child, and infant CPR, Foreign Body Airway Obstruction, and AED training. Cost includes the use of a students’ textbook, written and practical exams, and course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Basic Life Support (BLS) with CPR for Healthcare Professionals -  Refresher", TypicalPrice = 50 },
                        new { CourseId = 3, BookAvailable = false, BookPrice = 0m, CategoryId = 3, Description = "For those who have successfully completed the online portion of either BLS course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "BLS Online Recertification – Part 2", PrereqId = 3, TypicalPrice = 0 },
                        new { CourseId = 4, BookAvailable = true, BookPrice = 15m, CategoryId = 4, Description = "A 2-3 hour course designed to teach the lay rescuer (security guards, personal trainers, church organization teachers, etc.) how to recognize and treat life-threatening emergencies whose job requires a course completion card documenting one-rescuer adult and/or pediatric CPR, Foreign Body Airway Obstruction, and AED training. Cost includes the use of a textbook, practice exam, and course completion certificate(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver CPR/AED ", TypicalPrice = 50 },
                        new { CourseId = 5, BookAvailable = true, BookPrice = 15m, CategoryId = 2, Description = "A 4 hour course designed for the general public or lay rescuer whose job requires a first aid course completion card.  The course provides the skills to effectively asses and maintain life from the critical minutes of an emergency until the arrival of emergency service personnel.  Depending on which modules the candidate wishes to take, the basic first aid course consists of General Principles, Medical Emergencies, and Injury Emergencies.  Also includes CPR and AED training, and Environmental Emergencies. Cost includes use of a textbook, practice exam, and course completion certificate(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver First Aid ", TypicalPrice = 50 },
                        new { CourseId = 6, BookAvailable = false, BookPrice = 0m, CategoryId = 1, Description = "A 6-8 hour First Aid course designed for childcare workers whose job requires a pediatric-specific first aid completion card.  This course provides the skills to effectively asses and maintain a child’s life in the critical minutes following an emergency until the arrival of emergency personnel.  This course covers all State of Louisiana required modules including Child Care specific topics, General Principles, Medical Emergencies, Injury Emergencies, and Environmental Emergencies.  Also includes CPR and AED training for Adult, Children, and Infants. Cost includes use of a textbook, skills, and course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver Pediatric First Aid Course (Daycare/Childcare Providers)", TypicalPrice = 50 },
                        new { CourseId = 7, BookAvailable = false, BookPrice = 0m, CategoryId = 2, Description = "A 2 ½ hour entry level awareness program designed for the general public, parents, babysitters, grandparents, churches, clubs, etc.  The course covers American Heart Association guidelines for the one-rescuer adult including Pediatric CPR, relief of Foreign Body Airway Obstructions, the chain of survival, Basic First Aid, and recognizing the signs of a heart attack and stroke. Cost includes a student textbook.New 2016 Guidelines!", Name = "Family and Friends CPR (course designed for general public; non-certification course)", TypicalPrice = 50 },
                        new { CourseId = 8, BookAvailable = false, BookPrice = 0m, CategoryId = 2, Description = "This is a 16 - 20 hour course for those who wish to become AHA Instructor Candidates able to teach various levels of American Heart Association CPR.  Course is taught over 2 or 3 days. Successful completion of AHA BLS for Healthcare Providers Course, as well as each module instructor candidates wish to teach(Heartsaver First Aid, Heartsaver CPR / AED, etc.), and scoring 90 % or better on written examination(within 90 days of the instructor course) is required for completion. A letter of recommendation and completion of Core Instructor Course is required before applying. Cost includes all student level books, instructor manuals, practical exams, and test.New 2015 Guidelines!", Name = "BLS CPR for Healthcare Providers, Instructor Course", PrereqId = 1, TypicalPrice = 50 },
                        new { CourseId = 9, BookAvailable = false, BookPrice = 0m, CategoryId = 1, Description = "For those who have successfully completed the online portion of the Heartsaver CPR/AED course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "CPR/AED Online Recertification – Part 2", PrereqId = 4, TypicalPrice = 50 },
                        new { CourseId = 10, BookAvailable = false, BookPrice = 0m, CategoryId = 2, Description = "For those who have successfully completed the online portion of the Heartsaver First Aid course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "First Aid Online Recertification – Part 2", PrereqId = 5, TypicalPrice = 50 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookBought");

                    b.Property<bool>("Confirmed");

                    b.Property<int>("InstanceId");

                    b.Property<bool>("Paid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("UserId");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new { EnrollmentId = 1, BookBought = false, Confirmed = true, InstanceId = 1, Paid = false, Status = "E", UserId = 12 },
                        new { EnrollmentId = 17, BookBought = false, Confirmed = true, InstanceId = 7, Paid = false, Status = "E", UserId = 9 },
                        new { EnrollmentId = 2, BookBought = false, Confirmed = true, InstanceId = 1, Paid = true, Status = "E", UserId = 2 },
                        new { EnrollmentId = 18, BookBought = false, Confirmed = true, InstanceId = 7, Paid = true, Status = "E", UserId = 10 },
                        new { EnrollmentId = 3, BookBought = false, Confirmed = true, InstanceId = 1, Paid = true, Status = "E", UserId = 3 },
                        new { EnrollmentId = 19, BookBought = false, Confirmed = true, InstanceId = 8, Paid = false, Status = "E", UserId = 10 },
                        new { EnrollmentId = 4, BookBought = false, Confirmed = false, InstanceId = 2, Paid = true, Status = "E", UserId = 4 },
                        new { EnrollmentId = 20, BookBought = false, Confirmed = true, InstanceId = 8, Paid = true, Status = "E", UserId = 11 },
                        new { EnrollmentId = 5, BookBought = false, Confirmed = false, InstanceId = 2, Paid = true, Status = "E", UserId = 5 },
                        new { EnrollmentId = 21, BookBought = false, Confirmed = true, InstanceId = 8, Paid = false, Status = "E", UserId = 12 },
                        new { EnrollmentId = 6, BookBought = false, Confirmed = true, InstanceId = 2, Paid = true, Status = "E", UserId = 6 },
                        new { EnrollmentId = 22, BookBought = false, Confirmed = false, InstanceId = 9, Paid = true, Status = "E", UserId = 13 },
                        new { EnrollmentId = 7, BookBought = false, Confirmed = true, InstanceId = 3, Paid = true, Status = "E", UserId = 7 },
                        new { EnrollmentId = 23, BookBought = false, Confirmed = true, InstanceId = 9, Paid = true, Status = "E", UserId = 14 },
                        new { EnrollmentId = 8, BookBought = false, Confirmed = false, InstanceId = 3, Paid = false, Status = "E", UserId = 8 },
                        new { EnrollmentId = 24, BookBought = false, Confirmed = true, InstanceId = 9, Paid = true, Status = "E", UserId = 14 },
                        new { EnrollmentId = 9, BookBought = false, Confirmed = true, InstanceId = 3, Paid = true, Status = "E", UserId = 13 },
                        new { EnrollmentId = 25, BookBought = false, Confirmed = true, InstanceId = 10, Paid = false, Status = "E", UserId = 14 },
                        new { EnrollmentId = 10, BookBought = false, Confirmed = true, InstanceId = 4, Paid = false, Status = "E", UserId = 2 },
                        new { EnrollmentId = 26, BookBought = false, Confirmed = true, InstanceId = 10, Paid = true, Status = "E", UserId = 15 },
                        new { EnrollmentId = 11, BookBought = false, Confirmed = true, InstanceId = 4, Paid = true, Status = "E", UserId = 3 },
                        new { EnrollmentId = 27, BookBought = false, Confirmed = true, InstanceId = 10, Paid = true, Status = "E", UserId = 16 },
                        new { EnrollmentId = 12, BookBought = false, Confirmed = true, InstanceId = 5, Paid = true, Status = "E", UserId = 4 },
                        new { EnrollmentId = 28, BookBought = false, Confirmed = false, InstanceId = 11, Paid = false, Status = "E", UserId = 17 },
                        new { EnrollmentId = 13, BookBought = false, Confirmed = true, InstanceId = 5, Paid = true, Status = "E", UserId = 5 },
                        new { EnrollmentId = 29, BookBought = false, Confirmed = true, InstanceId = 12, Paid = true, Status = "E", UserId = 3 },
                        new { EnrollmentId = 14, BookBought = false, Confirmed = false, InstanceId = 6, Paid = true, Status = "E", UserId = 6 },
                        new { EnrollmentId = 30, BookBought = false, Confirmed = true, InstanceId = 12, Paid = true, Status = "E", UserId = 17 },
                        new { EnrollmentId = 15, BookBought = false, Confirmed = true, InstanceId = 6, Paid = true, Status = "E", UserId = 7 },
                        new { EnrollmentId = 31, BookBought = false, Confirmed = false, InstanceId = 13, Paid = true, Status = "E", UserId = 2 },
                        new { EnrollmentId = 16, BookBought = false, Confirmed = true, InstanceId = 6, Paid = false, Status = "E", UserId = 8 },
                        new { EnrollmentId = 32, BookBought = false, Confirmed = true, InstanceId = 13, Paid = true, Status = "E", UserId = 3 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Instance", b =>
                {
                    b.Property<int>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookAvailable");

                    b.Property<double>("BookPrice");

                    b.Property<int>("CourseId");

                    b.Property<int>("InstructorId");

                    b.Property<int>("LocationId");

                    b.Property<double>("Price");

                    b.Property<int>("Seats");

                    b.Property<DateTimeOffset>("StartDate");

                    b.HasKey("InstanceId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("LocationId");

                    b.ToTable("Instance");

                    b.HasData(
                        new { InstanceId = 1, BookAvailable = true, BookPrice = 50.0, CourseId = 1, InstructorId = 1, LocationId = 1, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 7, 1, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 2, BookAvailable = true, BookPrice = 30.0, CourseId = 1, InstructorId = 2, LocationId = 2, Price = 45.0, Seats = 10, StartDate = new DateTimeOffset(new DateTime(2018, 7, 22, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 3, BookAvailable = true, BookPrice = 50.0, CourseId = 1, InstructorId = 3, LocationId = 3, Price = 45.0, Seats = 30, StartDate = new DateTimeOffset(new DateTime(2018, 8, 2, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 4, BookAvailable = true, BookPrice = 250.0, CourseId = 2, InstructorId = 4, LocationId = 1, Price = 45.0, Seats = 10, StartDate = new DateTimeOffset(new DateTime(2018, 8, 12, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 5, BookAvailable = true, BookPrice = 50.0, CourseId = 2, InstructorId = 5, LocationId = 2, Price = 45.0, Seats = 30, StartDate = new DateTimeOffset(new DateTime(2018, 9, 12, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 6, BookAvailable = true, BookPrice = 10.0, CourseId = 2, InstructorId = 6, LocationId = 3, Price = 45.0, Seats = 10, StartDate = new DateTimeOffset(new DateTime(2018, 9, 21, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 7, BookAvailable = true, BookPrice = 60.0, CourseId = 3, InstructorId = 7, LocationId = 1, Price = 45.0, Seats = 12, StartDate = new DateTimeOffset(new DateTime(2018, 9, 30, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 8, BookAvailable = true, BookPrice = 90.0, CourseId = 3, InstructorId = 1, LocationId = 2, Price = 45.0, Seats = 10, StartDate = new DateTimeOffset(new DateTime(2018, 9, 29, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 9, BookAvailable = true, BookPrice = 50.0, CourseId = 3, InstructorId = 2, LocationId = 3, Price = 45.0, Seats = 10, StartDate = new DateTimeOffset(new DateTime(2018, 10, 1, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 10, BookAvailable = true, BookPrice = 100.0, CourseId = 4, InstructorId = 3, LocationId = 1, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 10, 24, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 11, BookAvailable = true, BookPrice = 50.0, CourseId = 4, InstructorId = 4, LocationId = 1, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 10, 25, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 12, BookAvailable = true, BookPrice = 50.0, CourseId = 5, InstructorId = 5, LocationId = 1, Price = 45.0, Seats = 15, StartDate = new DateTimeOffset(new DateTime(2018, 11, 1, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 13, BookAvailable = true, BookPrice = 30.0, CourseId = 5, InstructorId = 6, LocationId = 2, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 11, 11, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 14, BookAvailable = true, BookPrice = 50.0, CourseId = 5, InstructorId = 7, LocationId = 2, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 11, 13, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) },
                        new { InstanceId = 15, BookAvailable = true, BookPrice = 300.0, CourseId = 5, InstructorId = 1, LocationId = 2, Price = 45.0, Seats = 25, StartDate = new DateTimeOffset(new DateTime(2018, 11, 14, 8, 6, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<int>("Zipcode");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new { LocationId = 1, City = "Hammond", Name = "Hammond Location", State = "LA", Street = "104 Smith Street", Zipcode = 70403 },
                        new { LocationId = 2, City = "Tickfaw", Name = "Tickfaw Location", State = "LA", Street = "92 Hill Street", Zipcode = 70442 },
                        new { LocationId = 3, City = "Independence", Name = "Independence Location", State = "LA", Street = "12044 Hwy 40", Zipcode = 70443 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio");

                    b.Property<string>("Picture");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new { StaffId = 1, Bio = "I am Staff 1!", Picture = "Placeholder" },
                        new { StaffId = 2, Bio = "I am Staff 2!", Picture = "Placeholder" },
                        new { StaffId = 3, Bio = "I am Staff 3!", Picture = "Placeholder" },
                        new { StaffId = 4, Bio = "I am Staff 4!", Picture = "Placeholder" },
                        new { StaffId = 5, Bio = "I am Staff 5!", Picture = "Placeholder" },
                        new { StaffId = 6, Bio = "I am Staff 6!", Picture = "Placeholder" },
                        new { StaffId = 7, Bio = "I am Staff 7!", Picture = "Placeholder" }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Role");

                    b.Property<byte[]>("Salt");

                    b.Property<int?>("StaffId");

                    b.HasKey("UserId");

                    b.HasIndex("StaffId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 1, Email = "admin@admin.com", FirstName = "Becky", LastName = "Smith", Password = "4MzHj23ikIsyimD469f0fZuAoZWiN5fkXa9/GMNntp8=", Phone = "1112223333", Role = "Admin", Salt = new byte[] { 39, 72, 105, 193, 151, 178, 7, 125, 201, 38, 69, 187, 219, 98, 81, 29 } },
                        new { UserId = 2, Email = "student1@student.com", FirstName = "Paul", LastName = "Dig", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 1 },
                        new { UserId = 3, Email = "student2@student.com", FirstName = "Mike", LastName = "Waters", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 4, Email = "student3@student.com", FirstName = "Russel", LastName = "Chavers", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 5, Email = "student4@student.com", FirstName = "Sharon", LastName = "Manino", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 6, Email = "student5@student.com", FirstName = "Amy", LastName = "Hillbond", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 2 },
                        new { UserId = 7, Email = "student6@student.com", FirstName = "Bill", LastName = "Everet", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 8, Email = "student7@student.com", FirstName = "Trenton", LastName = "Hillsong", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 3 },
                        new { UserId = 9, Email = "student8@student.com", FirstName = "Colin", LastName = "Livers", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 10, Email = "student9@student.com", FirstName = "Babe", LastName = "Ruth", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 11, Email = "student10@student.com", FirstName = "Tim", LastName = "Hammond", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 4 },
                        new { UserId = 12, Email = "student11@student.com", FirstName = "Gary", LastName = "Aimes", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 13, Email = "student12@student.com", FirstName = "Lucy", LastName = "Vilardo", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 5 },
                        new { UserId = 14, Email = "student13@student.com", FirstName = "Tom", LastName = "Avers", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 6 },
                        new { UserId = 15, Email = "student14@student.com", FirstName = "Amanda", LastName = "Catalonato", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } },
                        new { UserId = 16, Email = "student15@student.com", FirstName = "Donald", LastName = "Hill", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 }, StaffId = 7 },
                        new { UserId = 17, Email = "student16@student.com", FirstName = "Richard", LastName = "Newman", Password = "PZJm1P8KQaqGmsuo0VrPwO5qcCpv6QcjRgX+DyGVp1M=", Phone = "1112223333", Role = "User", Salt = new byte[] { 187, 236, 157, 178, 112, 157, 31, 89, 240, 10, 110, 241, 243, 98, 118, 78 } }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Course", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Category", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.Course", "Prereq")
                        .WithMany("Courses")
                        .HasForeignKey("PrereqId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Enrollment", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Instance", "Instance")
                        .WithMany("Enrollments")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Instance", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Course", "Course")
                        .WithMany("Instances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.User", "Instructor")
                        .WithMany("Instances")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.Location", "Location")
                        .WithMany("Instances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.User", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Staff", "Staff")
                        .WithMany("User")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
