// <auto-generated />
using System;
using KSS.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190106174539_initial-production")]
    partial class initialproduction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KSS.Areas.Admin.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new { CategoryId = 1, Description = "Learn CPR, a medical procedure involving specific compression of a patient's chest, performed in an attempt to bring back the blood circulation and breathing of a person who has suffered cardiac arrest.", Name = "CPR", Title = "CPR, Life Support, and First Aid" },
                        new { CategoryId = 2, Description = "Interested in becoming an EMT? An EMT is a specially trained technician certified to provide basic emergency services before and during transportation to a hospital.", Name = "EMT", Title = "Emergency Medical Technician" },
                        new { CategoryId = 3, Description = "In case of a medical emergency, learn techniques and procedures for helping others in need of immediate attention and treating minor wounds.", Name = "EMR", Title = "Emergency Medical Responder" },
                        new { CategoryId = 4, Description = "These courses teach applicable safety practices for individuals such as swim coaches, lifeguard instructors, and even professional rescuers.", Name = "AQU", Title = "Aquatic Rescue" },
                        new { CategoryId = 5, Description = "Learn how to properly conduct child safety seat checks and be informed on the best way to utilize and understand seat belts and child restraint systems while in motorized vehicles.", Name = "CAR", Title = "Car Seat Safety" },
                        new { CategoryId = 6, Description = "Babysitting can sometimes be difficult, but our courses teach babysitting skills, such as leadership, keeping children safe, and helping kids to behave, to anyone who wants to learn or even grow a babysitting business.", Name = "BBS", Title = "Babysitting Safety" }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BookAvailable");

                    b.Property<double?>("BookPrice");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("PrereqId");

                    b.Property<int>("TypicalPrice");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrereqId");

                    b.ToTable("Course");

                    b.HasData(
                        new { CourseId = 1, BookAvailable = false, BookPrice = 0.0, CategoryId = 3, Description = "Emergency Medical Responder 60-hour course will prepare the EMR student to provide prehospital assessment and care for patients of all ages with a variety of medical conditions and traumatic injuries. Area of study includes an introduction to emergency medical systems, roles and responsibilities of EMR’s, anatomy and physiology, medical emergencies, trauma, and special considerations for working in the prehospital setting. EMR students will be able to do the following: describe the roles of EMS in the healthcare system, demonstrate the professional attributes expected of the EMRs, perform the roles and responsibilities of an EMR with regards to personal safety as well as safety of others, perform the duties of an EMR with regard to medical - legal and ethical issues, identify and perform lifesaving intervention ns to manage a patient’s airway, breathing and circulation, assess and manage medical and traumatic issues, and apply principles of emergency medical services.", Name = "Emergency Medical Responder", TypicalPrice = 0 },
                        new { CourseId = 2, BookAvailable = false, BookPrice = 0.0, CategoryId = 3, Description = "An EMR 16-hour recertification course for those with preexisting EMR certification.  This course will prepare the EMR student to provide prehospital assessment and care for patients of all ages with a variety of medical conditions and traumatic injuries. Area of study includes an introduction to emergency medical systems, roles and responsibilities of EMR’s, anatomy and physiology, medical emergencies, trauma, and special considerations for working in the prehospital setting. EMR students will be able to do the following: describe the roles of EMS in the healthcare system, demonstrate the professional attributes expected of the EMRs, perform the roles and responsibilities of an EMR with regards to personal safety as well as safety of others, perform the duties of an EMR with regard to medical - legal and ethical issues, identify and perform lifesaving intervention ns to manage a patient’s airway, breathing and circulation, assess and manage medical and traumatic issues, and apply principles of emergency medical services.", Name = "EMR Recertification", PrereqId = 1, TypicalPrice = 0 },
                        new { CourseId = 3, BookAvailable = false, BookPrice = 0.0, CategoryId = 2, Description = "The Emergency Medical Technician (EMT) 160-hour program is designed to train the lay person in emergency care in the pre-hospital environment. This is the entry level in the Emergency Medical Services (EMS) field.  The program follows the current Department of Transportation (DOT) EMT curriculum. The program instructs the student in medical practices available to prehospital personnel, patient assessment and management of trauma and medical emergencies, airway management, resuscitation and pharmacological interventions. This program will develop the student’s confidence, knowledge and skills in performing critical assessment and management of patients with medical and trauma elated life threats.", Name = "Emergency Medical Technician", TypicalPrice = 0 },
                        new { CourseId = 4, BookAvailable = false, BookPrice = 0.0, CategoryId = 2, Description = "An EMT 20-hour recertification course for those with preexisting EMT certification. This program is designed to train the lay person in emergency care in the pre-hospital environment. This is the entry level in the Emergency Medical Services (EMS) field.  The program follows the current Department of Transportation (DOT) EMT curriculum. The program instructs the student in medical practices available to prehospital personnel, patient assessment and management of trauma and medical emergencies, airway management, resuscitation and pharmacological interventions. This program will develop the student’s confidence, knowledge and skills in performing critical assessment and management of patients with medical and trauma elated life threats.", Name = "EMT Recertification", PrereqId = 3, TypicalPrice = 0 },
                        new { CourseId = 5, BookAvailable = true, BookPrice = 25.0, CategoryId = 1, Description = "A 4 ½ hour initial course designed for Healthcare Professionals.  The course covers Adult, Child, and Infant one-rescuer CPR AED, as well as a new focused emphasis on teamwork with the adult, child, and infant two-person rescue.  Topics also include Rescue Breathing and Foreign Body Airway Obstruction. Cost includes the use of a textbook, written and practical exams, and a course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Basic Life Support", TypicalPrice = 50 },
                        new { CourseId = 6, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "A 4 hour refresher course for the Healthcare Professional; this course offers guidelines in one and two-rescuer adult, child, and infant CPR, Foreign Body Airway Obstruction, and AED training. Cost includes the use of a students’ textbook, written and practical exams, and course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Basic Life Support w/ CPR Refr", TypicalPrice = 50 },
                        new { CourseId = 7, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "For those who have successfully completed the online portion of either BLS course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "BLS Online Recert – Part 2", PrereqId = 5, TypicalPrice = 0 },
                        new { CourseId = 8, BookAvailable = true, BookPrice = 15.0, CategoryId = 1, Description = "A 2-3 hour course designed to teach the lay rescuer (security guards, personal trainers, church organization teachers, etc.) how to recognize and treat life-threatening emergencies whose job requires a course completion card documenting one-rescuer adult and/or pediatric CPR, Foreign Body Airway Obstruction, and AED training. Cost includes the use of a textbook, practice exam, and course completion certificate(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver CPR/AED ", TypicalPrice = 50 },
                        new { CourseId = 9, BookAvailable = true, BookPrice = 15.0, CategoryId = 1, Description = "A 4 hour course designed for the general public or lay rescuer whose job requires a first aid course completion card.  The course provides the skills to effectively asses and maintain life from the critical minutes of an emergency until the arrival of emergency service personnel.  Depending on which modules the candidate wishes to take, the basic first aid course consists of General Principles, Medical Emergencies, and Injury Emergencies.  Also includes CPR and AED training, and Environmental Emergencies. Cost includes use of a textbook, practice exam, and course completion certificate(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver First Aid ", TypicalPrice = 50 },
                        new { CourseId = 10, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "A 6-8 hour First Aid course designed for childcare workers whose job requires a pediatric-specific first aid completion card.  This course provides the skills to effectively asses and maintain a child’s life in the critical minutes following an emergency until the arrival of emergency personnel.  This course covers all State of Louisiana required modules including Child Care specific topics, General Principles, Medical Emergencies, Injury Emergencies, and Environmental Emergencies.  Also includes CPR and AED training for Adult, Children, and Infants. Cost includes use of a textbook, skills, and course completion certification(good for 2 years).New 2015 Guidelines!", Name = "Heartsaver Pediatric First Aid", TypicalPrice = 50 },
                        new { CourseId = 11, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "A 2 ½ hour entry level awareness program designed for the general public, parents, babysitters, grandparents, churches, clubs, etc.  The course covers American Heart Association guidelines for the one-rescuer adult including Pediatric CPR, relief of Foreign Body Airway Obstructions, the chain of survival, Basic First Aid, and recognizing the signs of a heart attack and stroke. Cost includes a student textbook.New 2016 Guidelines!", Name = "Family and Friends CPR", TypicalPrice = 50 },
                        new { CourseId = 12, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "This is a 16 - 20 hour course for those who wish to become AHA Instructor Candidates able to teach various levels of American Heart Association CPR.  Course is taught over 2 or 3 days. Successful completion of AHA BLS for Healthcare Providers Course, as well as each module instructor candidates wish to teach(Heartsaver First Aid, Heartsaver CPR / AED, etc.), and scoring 90 % or better on written examination(within 90 days of the instructor course) is required for completion. A letter of recommendation and completion of Core Instructor Course is required before applying. Cost includes all student level books, instructor manuals, practical exams, and test.New 2015 Guidelines!", Name = "BLS & CPR, Instructor", PrereqId = 5, TypicalPrice = 50 },
                        new { CourseId = 13, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "For those who have successfully completed the online portion of the Heartsaver CPR/AED course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "CPR/AED Online Recert 2", PrereqId = 8, TypicalPrice = 50 },
                        new { CourseId = 14, BookAvailable = false, BookPrice = 0.0, CategoryId = 1, Description = "For those who have successfully completed the online portion of the Heartsaver First Aid course.  Students MUST provide a copy of the online course completion certificate. Cost includes practice time, exam, and course completion certificate(good for 2 years)", Name = "First Aid Online Recert 2", PrereqId = 9, TypicalPrice = 50 },
                        new { CourseId = 15, BookAvailable = false, BookPrice = 0.0, CategoryId = 6, Description = "This 14 hour, 2 day class following American Red Cross standards will educate the babysitter on skills necessary to provide quality care to children of all ages.  Participants must be ages 11 and older and will learn Adult/Child/Infant CPR and AED, basic first aid, child behavior, age-appropriate activities, basic child care (including bottling, feeding, and diapering), and professionalism.  This courses teaches techniques necessary for all babysitters.", Name = "ARC Babysitting  BOOT CAMP", TypicalPrice = 50 },
                        new { CourseId = 16, BookAvailable = false, BookPrice = 0.0, CategoryId = 4, Description = "The purpose of the American Red Cross Lifeguard Course is to provide entry-level lifeguard participants with knowledge and skills to prevent, recognize, and respond to aquatic emergencies.  The lifeguard will also learn care for breathing and cardiac emergencies, as well as first aid skills.  This is a 25 hour course taught by a certified ARC instructor.  Students must be 15 years or older and able to swim 300 yards continuously demonstrating breath control and rhythmic breating.  Candidates may swim using front crawl, breaststroke, or combination only; side or back swimming is not allowed. Goggles may be worn for this portion.  Candidates must also be able to tread water for 2 minutes using only legs (arms will be placed under armpits) and complete a timed event within 1 minute 40 seconds.  Candidates will be required to swim 20 yards without goggles and surface dive (feet or head first) to a depth of 7 to 10 feet to retrieve a 10 pound object.  Candidates must also exit the water without using a ladder or steps.", Name = "ARC Initial Lifeguard", TypicalPrice = 50 },
                        new { CourseId = 17, BookAvailable = false, BookPrice = 0.0, CategoryId = 4, Description = "Current certified lifeguards with valid American Red Cross Lifeguarding/CPR/AED/First aid certification who have expired more than 30 days.  Students must bring proof of valid ARC Lifeguarding, First Aid, and CPR/AED for the Professional Rescuer certification.  Students will be required to swim 300 yards, tread water using legs only for 2 minutes, and retrieve a 10 pound weird from a 7-10 foot depth, swim 20 yards wihth the weight, and exit the pool without using ladder or steps within 100 seconds.  Students will recieve a 2 year ARC certification in Lifeguard, First Aid, and CPR/AED", Name = "ARC Lifeguard Recert", PrereqId = 16, TypicalPrice = 50 },
                        new { CourseId = 18, BookAvailable = false, BookPrice = 0.0, CategoryId = 4, Description = "The purpose of this instructor course is to ttrain candidates to teach courses and presentation in the American Red Cross Swimming and Water Safety program including Parent and Child Aquatics, Preschool Aquatics, Learn-to-Swim, Adult Swim, Private Lessons, Water Safety Courses (including Safety Training for Swim Coaches) and Water Safety Presentations.  Candidates must be at least 16 years old and demonstrate the ability to perform the following swimming skills: Front Crawl, Back Crawl, Breaststroke, Elementary Backstroke, Sidestroke, and Butterfly, all for 25 yards.  Candidates must be able to maintain position on back for 1 minute in deep water (floating or sculling) and must tread water for 1 minute.  The instructor-lead course is 31 hours.  To be certified, candidates must successfully complete the online Intro to the ARC Water Safety Course, complete the Precourse Skills Session, attend and participate in all course sessions, complete class activities including the four practice-teaching assignments, demonstrate instructor-level skill competency in all scenarios, and score a minimum of 80 percent on the instructor course final written exam.", Name = "ARC Water Safety Instructor", PrereqId = 16, TypicalPrice = 50 },
                        new { CourseId = 19, BookAvailable = false, BookPrice = 0.0, CategoryId = 4, Description = "The purpose of the American Red Cross Lifeguard Instructor course is to train candidates to teach the American Red Cross Lifeguarding, Lifeguard Blending Learning, Shallow Water Lifeguard, Water Park Skills, CPR/AED for the Professional Rescuers and Health Care Providers, Administering Emergency Oxygen and Bloodborne Pathogens Training courses and modules.  Candidates must be at least 17 years old, possess current ARC Lifeguarding/CPR/AED/First Aid certification, complete the online Orientation to the ARC and Orientation to the Lifeguard Instructor course and Precourse Exam, successfully complete the Precourse session, and Obtain the Lifeguard Instructor's Manual and Lifeguarding Manual.  To be certified, candidates must successfully complete the online Intro to the ARC Lifeguard Instructor Course, complete the Precourse Skills Session, attend and participate in all course sessions, complete class activities including the four practice-teaching assignments, demonstrate instructor-level skill competency in all scenarios, and score a minimum of 80 percent on the instructor course final written exam.", Name = "ARC Lifeguard Instructor", PrereqId = 16, TypicalPrice = 50 },
                        new { CourseId = 20, BookAvailable = false, BookPrice = 0.0, CategoryId = 5, Description = "This is a free service by certified child passenger safety technicians to lower childhood deaths and injuries.  To stay informed of events and education, please follow Buckle Up Louisiana on Facebook.  Nicole Dufrene can assist anyone who has questions concerning car safety seat information FREE of charge. Her email is: nicoledufrene0301@gmail.com.  Additional information can be found at The National Highway and Traffic Safety website https://www.nhtsa.gov/.  Also visit https://www.safekids.org/child-passenger-safety to learn more about the organization that regulates the  curriculum for our classes and also has a find a fitting station near you.", Name = "Car Seat Safety", TypicalPrice = 0 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BookBought");

                    b.Property<DateTime?>("Confirmed");

                    b.Property<int>("InstanceId");

                    b.Property<bool>("Paid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("UserId");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Instance", b =>
                {
                    b.Property<int>("InstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BookAvailable");

                    b.Property<double?>("BookPrice");

                    b.Property<int>("CourseId");

                    b.Property<bool>("Graded");

                    b.Property<int>("InstructorId");

                    b.Property<int>("LocationId");

                    b.Property<double>("Price");

                    b.Property<int>("Seats");

                    b.Property<DateTimeOffset>("StartDate");

                    b.HasKey("InstanceId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("LocationId");

                    b.ToTable("Instance");
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<int>("Zipcode");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new { LocationId = 1, City = "Covington", Name = "St. Tammany Fire District 12", State = "LA", Street = "19375 LA-36", Zipcode = 70433 },
                        new { LocationId = 2, City = "Husser", Name = "Husser Fire Department", State = "LA", Street = "56298 LA-445", Zipcode = 70442 },
                        new { LocationId = 3, City = "Independence", Name = "Independence Fire", State = "LA", Street = "12044 Hwy 40", Zipcode = 70443 },
                        new { LocationId = 4, City = "Mandeville", Name = "Mandeville Fire Department", State = "LA", Street = "24301 Highway 190", Zipcode = 70448 },
                        new { LocationId = 5, City = "Slidell", Name = "Slidell Fire Department", State = "LA", Street = "375 Bouscaren St", Zipcode = 70458 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.StaffBio", b =>
                {
                    b.Property<int>("StaffBioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<string>("Picture");

                    b.Property<int>("UserId");

                    b.HasKey("StaffBioId");

                    b.HasIndex("UserId");

                    b.ToTable("Bio");

                    b.HasData(
                        new { StaffBioId = 1, Bio = "Beckey Smith is the owner of Keeping Safety Smart. With over 20 years of emergency/life saver teaching experience, Ms. Smith founded Keeping Safety Smart in 2015.", Picture = "https://i.ibb.co/KVjPPp7/beckeysmith.jpg", UserId = 1 },
                        new { StaffBioId = 2, Bio = "Nicole Dufrene EMR has a passion to help protect our littles one from the number one cause of children's death motor vehicle accidents.  She is driven to help educate about how to properly install a car seat and make sure your little ones are safe and secured.", Picture = "https://i.ibb.co/dt0W5kH/nicoledufrene.jpg", UserId = 2 },
                        new { StaffBioId = 3, Bio = "Dennis Pitts NREMT is a seasoned fire fighter in the Tangipahoa Parish area.  He teaches all the CPR, first aid, and bureau of EM S classes.", Picture = "https://i.ibb.co/JBxJPv6/dennispitts.jpg", UserId = 3 },
                        new { StaffBioId = 4, Bio = "Clayton Cawyer NREMT has been teaching for several years in the CPR, first aid and Bureau of EMS classes as well as a fire fighter in the St. Tammany area. ", Picture = "https://i.ibb.co/GJdjzDw/claytoncawyer.png", UserId = 4 },
                        new { StaffBioId = 5, Bio = "Jodi Toliver MS is an instructor train the trainer and has been teach water classes for over 25 years.  She will also be helping to teach the American Red Cross babysitters class.", Picture = "https://i.ibb.co/G33Vh31/jodit.png", UserId = 5 },
                        new { StaffBioId = 6, Bio = "Savannah Rachel RN started her career as an EMT and has continued her education in the healthcare field.  She is currently working at East Jefferson Hospital and will be teaching the ACLS classes.", Picture = "https://i.ibb.co/nB1N37X/savannah-rachel.jpg", UserId = 6 },
                        new { StaffBioId = 7, Bio = "Jackie Smith BSN is finish her Masters degree in Nursing education she is a current cardiac nurse.  She will be teaching the ACLS classes.", Picture = "https://image.ibb.co/jkKE2A/user-placeholder.png", UserId = 7 }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Role");

                    b.Property<byte[]>("Salt");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 10, Email = "webmaster@keepingsafetysmart.com", FirstName = "Developer", LastName = "Developer", Password = "+PpaorYj4pAwGReVIzSFOFZ1ngFhvW9p1okX0em3gLw=", Phone = "1112223333", Role = "Admin", Salt = new byte[] { 56, 77, 183, 92, 241, 31, 235, 88, 132, 22, 169, 143, 163, 190, 6, 206 } },
                        new { UserId = 1, Email = "bsmithsafety@hotmail.com", FirstName = "Beckey", LastName = "Smith", Password = "+PpaorYj4pAwGReVIzSFOFZ1ngFhvW9p1okX0em3gLw=", Phone = "9855029425", Role = "Admin", Salt = new byte[] { 56, 77, 183, 92, 241, 31, 235, 88, 132, 22, 169, 143, 163, 190, 6, 206 } },
                        new { UserId = 2, Email = "nicoledufrene0301@gmail.com", FirstName = "Nicole", LastName = "Dufrene", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } },
                        new { UserId = 3, Email = "dennis@keepingsafetysmart.com", FirstName = "Dennis", LastName = "Pitts", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } },
                        new { UserId = 4, Email = "clayton@keepingsafetysmart.com", FirstName = "Clayton", LastName = "Cawyer", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } },
                        new { UserId = 5, Email = "jodi@keepingsafetysmart.com", FirstName = "Jodi", LastName = "Toliver", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } },
                        new { UserId = 6, Email = "savannah@keepingsafetysmart.com", FirstName = "Savannah", LastName = "Rachel", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } },
                        new { UserId = 7, Email = "jackie@keepingsafetysmart.com", FirstName = "Jackie", LastName = "Smith", Password = "D6L5boApNKVodbrG0LH0XuqdFMCKw4N+x62PrtbfvVg=", Phone = "1112223333", Role = "Staff", Salt = new byte[] { 97, 193, 27, 49, 22, 32, 200, 15, 59, 17, 251, 161, 22, 134, 92, 166 } }
                    );
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Course", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Category", "CourseCategory")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.Course", "Prereq")
                        .WithMany("Courses")
                        .HasForeignKey("PrereqId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Enrollment", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Instance", "Instance")
                        .WithMany("Enrollments")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.Instance", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.Course", "Course")
                        .WithMany("Instances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.User", "Instructor")
                        .WithMany("Instances")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KSS.Areas.Admin.Models.Location", "Location")
                        .WithMany("Instances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KSS.Areas.Admin.Models.StaffBio", b =>
                {
                    b.HasOne("KSS.Areas.Admin.Models.User", "User")
                        .WithMany("StaffBio")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
